#########Redis配置信息##########
##############################
spring:
  redis:
    #数据库索引
    database: 0
    #服务器地址
    cluster:
      nodes: 106.54.131.36:7001,106.54.131.36:7002,106.54.131.36:7003,106.54.131.36:7004,106.54.131.36:7005,106.54.131.36:7000
      max-redirects: 3
    #超时时间
    timeout: 5000
    jedis:
      pool:
        #Redis连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
  rabbitmq:
    #MQ端口
    host: 175.24.29.160
    port: 5672
    username: root
    password: root
    listener:
      simple:
        #消费者最小数量
        concurrency: 1
        # 消费者最大数量
        max-concurrency: 10
        acknowledge-mode: auto
    virtual-host: /